FORTRAN       = ifort
CPLUSPLUS     = icpc
CPLUSPLUS_MPI = mpiicpc
LAPACK_DIR    = $(MKLROOT)
FFTW_DIR      = /opt/fftw/3.3.8/intel/2018.update4
BOOST_DIR     = /opt/boost/1.39.0
ELPA_DIR      = /opt/elpa/2016.05.004/intel-2018.update4_mkl-2018.update4_intelmpi-2018.update4
